## 00. PyTorch Fundamentals

Resource Notebook: https://github.com/mrdbourke/pytorch-deep-learning

In [1]:
print("I am really excited to learn Pytorch")

I am really excited to learn Pytorch


In [2]:
!nvidia-smi

Fri Dec  9 06:02:12 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P0    31W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


In [4]:
!nvidia-smi

Fri Dec  9 06:02:19 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P0    31W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors
### Creating Tensors
Pytorch tensors are created using torch.Tensor(),
tensor data type

In [5]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# get tensor back as python int
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([9,9])
vector

tensor([9, 9])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX=torch.tensor([[2,3],[5,6]])
MATRIX

tensor([[2, 3],
        [5, 6]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX[1]

tensor([5, 6])

In [15]:
# TENSOR
TENSOR =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors

In [19]:
# creating a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2167, 0.4548, 0.4984, 0.7142],
        [0.5441, 0.9155, 0.5213, 0.5559],
        [0.3800, 0.7968, 0.9045, 0.4613]])

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor.shape

torch.Size([3, 4])

In [22]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #color channel, height, width
random_image_size_tensor

tensor([[[1.6774e-02, 4.5860e-01, 9.1605e-01,  ..., 2.7172e-01,
          2.3053e-01, 7.5011e-01],
         [1.5300e-01, 3.7445e-01, 4.6661e-01,  ..., 7.5950e-01,
          2.4742e-01, 7.9122e-01],
         [3.1330e-01, 6.5573e-01, 9.3772e-01,  ..., 4.6016e-01,
          1.0411e-01, 1.9993e-01],
         ...,
         [1.8401e-01, 5.9686e-01, 4.4596e-01,  ..., 4.9615e-01,
          2.9568e-01, 8.7754e-01],
         [1.4237e-01, 4.2209e-01, 6.2079e-01,  ..., 5.6687e-01,
          8.5075e-01, 8.8353e-01],
         [4.1993e-01, 7.4959e-04, 1.0144e-01,  ..., 6.1828e-01,
          5.2323e-01, 7.9811e-01]],

        [[7.8709e-01, 6.7025e-01, 3.7049e-01,  ..., 4.1741e-01,
          2.3059e-01, 1.0398e-01],
         [6.0257e-01, 9.4618e-01, 6.1484e-01,  ..., 2.3985e-01,
          1.1510e-01, 1.9258e-01],
         [5.3252e-01, 5.8177e-01, 9.0603e-01,  ..., 9.9427e-01,
          4.4751e-01, 6.9513e-01],
         ...,
         [1.6568e-01, 7.2977e-02, 3.1051e-01,  ..., 2.8900e-02,
          2.058

In [23]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [24]:
ra = torch.rand(size=(3,4))
ra

tensor([[0.1780, 0.5961, 0.1050, 0.5929],
        [0.0644, 0.7185, 0.1642, 0.6346],
        [0.1278, 0.6564, 0.1361, 0.8440]])

## Zeros and Ones

In [25]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ra*zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype #default datatype

torch.float32

In [29]:
ra.dtype

torch.float32

## creating a range of tensors and tensors like

In [30]:
# use torch.range() 
torch.range(0,10)

<ipython-input-30-62974d24b19e>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
onetoten= torch.arange(0,10)
onetoten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
one_to_thousands =torch.arange(start=1, end=1000, step=50)
one_to_thousands

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])

In [33]:
torch.__version__

'1.13.0+cu116'

In [34]:
# creating tensors like
ten_zeros = torch.zeros_like(input=onetoten) #same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [35]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,10.0], dtype=torch.float16)
float_32_tensor

tensor([ 3.,  6., 10.], dtype=torch.float16)

In [36]:
float_32_tensor.dtype

torch.float16

In [37]:
float_3_tensor = torch.tensor([2.0,3.0,5.0], dtype =None, device = "cpu",
                              requires_grad=False
                              )
float_3_tensor
# dtype= what datatype the tensor is
# single precision is float 32 bit, half precision is 16 bit and for more precision use 64 bits
#device = what device is your tensor on
# requires_ grad = whether or not to track grradients with tensors operations

tensor([2., 3., 5.])

In [38]:
float_3_tensor.dtype

torch.float32

In [39]:
float_16_tensor = float_3_tensor.type(torch.float16) #changing data type
float_16_tensor

tensor([2., 3., 5.], dtype=torch.float16)

In [40]:
float_16_tensor.dtype

torch.float16

In [41]:
a=float_3_tensor*float_16_tensor
a

tensor([ 4.,  9., 25.])

In [42]:
a.dtype

torch.float32

In [43]:
int_32_tensor = torch.tensor([1,2,3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [44]:
int_32_tensor * float_16_tensor

tensor([ 2.,  6., 15.], dtype=torch.float16)

In [45]:
#create a tensor
some_tensor = torch.rand(size =(3,4))
some_tensor

tensor([[0.5979, 0.5272, 0.9803, 0.3639],
        [0.4581, 0.4123, 0.5751, 0.9495],
        [0.9266, 0.5357, 0.5105, 0.9005]])

In [46]:
# find out details about tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5979, 0.5272, 0.9803, 0.3639],
        [0.4581, 0.4123, 0.5751, 0.9495],
        [0.9266, 0.5357, 0.5105, 0.9005]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors ( Tensor Operations)
Tensor operations include
*addition
*subtraction
*multiplication
*division
*matrix multiplicatons

In [47]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor +100

tensor([101, 102, 103])

In [48]:
#multiply tensor by 10
tensor =tensor *10
tensor

tensor([10, 20, 30])

In [49]:
# subtract
tensor - 10

tensor([ 0, 10, 20])

In [50]:
# trying out pytorch inbuilt functions
torch.mul(tensor,10)

tensor([100, 200, 300])

## Matrix multiplication

In [51]:
# element wise multiplications

In [52]:
tensor*tensor

tensor([100, 400, 900])

In [53]:
print( tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [54]:
# matrix multiplications
torch.matmul(tensor, tensor)

tensor(1400)

In [55]:
 %%time
 value=0
 for i in range(len(tensor)):
   value += tensor[i] * tensor[i]
 print(value)

tensor(1400)
CPU times: user 566 µs, sys: 0 ns, total: 566 µs
Wall time: 576 µs


In [56]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 28 µs, sys: 4 µs, total: 32 µs
Wall time: 35.3 µs


tensor(1400)

### one of the most important error in deep learning is shape error

In [57]:
# inner dimentions must match
#resulting matrix shape is the the shape of outer dimentions

In [58]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [59]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.2615, 0.3416, 0.2122],
        [0.5888, 0.3948, 0.3610],
        [0.3855, 0.6389, 0.3551]])

In [60]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.0850, 1.3345],
        [0.9078, 0.8477]])

In [61]:
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])

In [62]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

to fix our tensor shape issue, we can manipulate the shape of one of our tensors by using the transpose. the **transpose** switches the axes or dimentions of the given tensor

In [63]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [64]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [65]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [66]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [67]:
print(f"Original shape : tensor_A ={tensor_A.shape}, tensor_B ={tensor_B.shape}")
print(f"New shape : tensor_A={tensor_A.shape} (same as above), tensor_B = {tensor_B.T.shape}")
output=torch.mm(tensor_A, tensor_B.T) #mm means matmul
print(f"output : {output}")
print(f"Output shape : {output.shape}")

Original shape : tensor_A =torch.Size([3, 2]), tensor_B =torch.Size([3, 2])
New shape : tensor_A=torch.Size([3, 2]) (same as above), tensor_B = torch.Size([2, 3])
output : tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape : torch.Size([3, 3])


Finding the min, max, mean, sum etc (tensor aggregation)

In [68]:
# create a tensor
x = torch.arange(0,100,10)
print(x)
x.dtype

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


torch.int64

In [69]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [70]:
# find the mean - note: the torch.mean() fucntion requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [71]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

positional min and max which means argmin, argmax

In [72]:
# find the position of tensor that has minimum value with argmin(), and return index position

torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [73]:
# find the position of tensor that has maximum value with argmax(), and return index position

torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [74]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### reshaping, stacking, squeezing, unsquezzing
* reshaping- reshape an input tensor to a defined shape
* view- return a view of an input tensor of a certain shape but keep the same memory as the original tensor
*stacking= combine multiple tensor on top of each other( vstack ) or side by side (hstack)
* squeeze - remove all "1" dimentions from a tensor
* unsqueeze - add a "1" dimention to the tensor
* permute - return a view of the input with dimentions permuted (swapped) in a certain way

In [76]:
# lets create a tensor
import torch
x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [79]:
# reshape
# add an extra dimention
#reshape has to be compatible with the original size
x_reshape =x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [82]:
x_reshape =x.reshape(9,1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [83]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [87]:
# change the view
# view use the same memory as the original tensor
#changing z, changing x as they share the same memory location
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [91]:
z[:1]=5
z,x

(tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]]),
 tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]))

In [92]:
x

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [104]:
# stack tensors at each other
x_stacked =torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [115]:
# squeeze, remove all single dimentions from the target tensor
x_squeeze =torch.squeeze(x_reshape)
x_squeeze, x_squeeze.shape

(tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.]), torch.Size([9]))

In [118]:
print(f"previous tensor : {x_reshape}")
print(f"previous tensor shape : {x_reshape.shape}")
print(f"\nafter squeezing, current tensor  {x_squeeze}")
print(f"after squezzing, current tensor shape : {x_squeeze.shape}")

previous tensor : tensor([[5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.],
        [5.]])
previous tensor shape : torch.Size([9, 1])

after squeezing, current tensor  tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])
after squezzing, current tensor shape : torch.Size([9])


In [124]:
# unsqueeze
# add a single dimention to a target tensor at a specific dim
x_unsqueeze =torch.unsqueeze(x,0)
x_unsqueeze_1 =torch.unsqueeze(x,1)
print(x_unsqueeze, x_unsqueeze.shape)
x_unsqueeze_1, x_unsqueeze_1.shape

tensor([[5., 5., 5., 5., 5., 5., 5., 5., 5.]]) torch.Size([1, 9])


(tensor([[5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.],
         [5.]]), torch.Size([9, 1]))

In [129]:
# permute
# rearrange the dimentions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # image tensor, height, width, color channel
x_permuted = x_original.permute(2,0,1)

print(f"previous shape before permutation : {x_original.shape}")
print(f"current shape after permutation : {x_permuted.shape}") # color channel, height, width

previous shape before permutation : torch.Size([224, 224, 3])
current shape after permutation : torch.Size([3, 224, 224])


In [134]:
# permutes returns another view of an original tensor, and view shares same memory
x_original[0,0,0]=12
x_original[0,0,0], x_permuted[0,0,0]

(tensor(12.), tensor(12.))

Indexing (Selecting data from tensors)
* indexing in pytorch is similar like indexing in NumPy

* Numpy use Array datatype, Pytorch use tensors

In [137]:
# create tensor
import torch
x= torch.arange(1,10).reshape(1,3,3)
# reshape has to be compatible with original dimentions
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [146]:
x[0,2,1], x[0][2][2]

(tensor(8), tensor(9))

In [148]:
# we can also use ":" to select "all" of a target dimentions
x[:,0,1]

tensor([2])

In [150]:
# get all values of 0th and 1st dimentions but only index 1 of 2nd dimentions

x[:,:,1]


tensor([[2, 5, 8]])

In [151]:
# get all values of the 0 dimention but only the 1 index value of 1st and 2nd dimention
x[:,1,1]

tensor([5])

In [152]:
# get index 0 of 0th and 1st dimention and all values of 2nd dimentions
x[0,0,:]

tensor([1, 2, 3])

In [153]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [154]:
#index on x to return 9
x[:,2,2]

tensor([9])

In [155]:
# index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

###Pytorch tensors and NumPy
NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.
* Data in NumPy array, want in PyTorch tensor -> torch.from_numpy(ndarray)

* PyTorch tensor-->NumPy -> torch.Tensor.numpy()

In [157]:
# NumPy array to tensor
import torch
import numpy as np
array =np.arange(1.0,10.0)
tensor= torch.from_numpy(array).type(torch.float32)
#when converting from numpy to pytorch, pytorch reflects numpy's default datatype float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [158]:
tensor.dtype

torch.float32

In [159]:
array.dtype

dtype('float64')

In [160]:
# tensor to NumPy array
tensor = torch.ones(8)
numpy_tensor = torch.Tensor.numpy(tensor)
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [161]:
numpy_tensor.dtype

dtype('float32')

In [162]:
# changing tensor/numpy array won't change the tensor/numpy array

##Pytorch Reproducibility
trying to take random out of random
* to reduce the randomness in neural network and PyTorch comes the concept of **random seed**

* essentially what the random seed does is "flavour" the randomness

In [165]:
torch.rand(3,3)

tensor([[0.2025, 0.6786, 0.1825],
        [0.6149, 0.7275, 0.9669],
        [0.4524, 0.0609, 0.4746]])

In [167]:
import torch
#creating two random tensor
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
#checking if they are equal
print( random_tensor_A == random_tensor_B)

tensor([[0.9574, 0.8856, 0.5877, 0.8459],
        [0.3992, 0.4949, 0.2985, 0.9549],
        [0.1947, 0.1348, 0.1329, 0.2029]])
tensor([[0.6286, 0.8312, 0.9391, 0.5379],
        [0.9362, 0.8536, 0.8236, 0.6294],
        [0.5205, 0.7831, 0.5231, 0.9728]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [171]:
# let's make some random and reproducible tensors
import torch
# set the random seed
RANDOM_SEED =42
# using random seed make the tensor values reproducible
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D= torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## running tensors and PyTorch objects on the GPU's and making faster computation
* GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + Pytorch behind the scene 



## getting GPU
* colab, colab pro
* use your own, requires set up
* use cloud computing like AWS, GCP, Azure

In [173]:
!nvidia-smi

Fri Dec  9 08:25:48 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P0    27W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

Check for GPU access with PyTorch

In [174]:
#CUDA is NVIDIA's programming iterface that allow us to do numerical computing on GPU
import torch
torch.cuda.is_available()

True

In [176]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else " cpu "
device

'cuda'

In [178]:
# count number of devices
torch.cuda.device_count()

1

## Putting tensors and models on the GPU

In [181]:
# create a tensor
tensor = torch.tensor([1,2,3], device ="cpu") # default cpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [183]:
# tensor on gpu
tensor_on_gpu = tensor.to(device) # move tensor on GPU
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

In [188]:
# numpy only works on cpu
# moving tensors back to cpu
tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
# tensor_back_on_cpu.numpy()
tensor_back_on_cpu

array([1, 2, 3])